@apiEndpoint = http://localhost:3000

// Get all tasks
GET {{apiEndpoint}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlhdCI6MTU5NzE2NjgyNSwiZXhwIjoxNTk3MTcwNDI1fQ.kmi1laKJ2ITLSiVeA9v7xEzo1bYKnaQE--wIULQejF0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlhdCI6MTU5NzE2NzE1MCwiZXhwIjoxNTk3MTcwNzUwfQ.j9cwEVVex3qjDibQKyCcL0-aYlpYVQUmMVz9UomHYvc

###

// Get task by ID
@taskId = 4
GET {{apiEndpoint}}/tasks/{{taskId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlhdCI6MTU5NzE2NjgyNSwiZXhwIjoxNTk3MTcwNDI1fQ.kmi1laKJ2ITLSiVeA9v7xEzo1bYKnaQE--wIULQejF0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlhdCI6MTU5NzE2NzE1MCwiZXhwIjoxNTk3MTcwNzUwfQ.j9cwEVVex3qjDibQKyCcL0-aYlpYVQUmMVz9UomHYvc

###

// Create a task
@taskTitle = My task 2
@taskDecription = Task desc
POST {{apiEndpoint}}/tasks
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlhdCI6MTU5NzE2NjgyNSwiZXhwIjoxNTk3MTcwNDI1fQ.kmi1laKJ2ITLSiVeA9v7xEzo1bYKnaQE--wIULQejF0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlhdCI6MTU5NzE2NzE1MCwiZXhwIjoxNTk3MTcwNzUwfQ.j9cwEVVex3qjDibQKyCcL0-aYlpYVQUmMVz9UomHYvc
Content-Type: application/json

{
  "title": "{{taskTitle}}",
  "description": "{{taskDecription}}"
}

###

// Delete a task
@taskDeleteId = 3

DELETE {{apiEndpoint}}/tasks/{{taskDeleteId}}
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlhdCI6MTU5NzE2NjgyNSwiZXhwIjoxNTk3MTcwNDI1fQ.kmi1laKJ2ITLSiVeA9v7xEzo1bYKnaQE--wIULQejF0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlhdCI6MTU5NzE2NzE1MCwiZXhwIjoxNTk3MTcwNzUwfQ.j9cwEVVex3qjDibQKyCcL0-aYlpYVQUmMVz9UomHYvc

###

// Update task status
@taskIdForUpdate = 1
@taskStatus = IN_PROGRESS

PATCH {{apiEndpoint}}/tasks/{{taskIdForUpdate}}/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlhdCI6MTU5NzE2NjgyNSwiZXhwIjoxNTk3MTcwNDI1fQ.kmi1laKJ2ITLSiVeA9v7xEzo1bYKnaQE--wIULQejF0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlhdCI6MTU5NzE2NzE1MCwiZXhwIjoxNTk3MTcwNzUwfQ.j9cwEVVex3qjDibQKyCcL0-aYlpYVQUmMVz9UomHYvc
Content-Type: application/json

{
  "status": "{{taskStatus}}"
}

###

// Search

GET {{apiEndpoint}}/tasks?status=OPEN&searchTerm=Task




###

// User sign up

POST {{apiEndpoint}}/auth/signup
Content-Type: application/json

{
  "username": "testuser2",
  "password": "Welcome1!"
}

###

// Sign in

POST {{apiEndpoint}}/auth/signin
Content-Type: application/json

{
  "username": "testuser2",
  "password": "Welcome1!"
}

###

// Test endpoint that requires authentication

POST {{apiEndpoint}}/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNTk3MTY2MDQ5LCJleHAiOjE1OTcxNjk2NDl9.6VUqS3wu2vu0Hhmt4_cu8ND1ORtMVZBdCESFpE9emzE