@apiEndpoint = http://localhost:3000

// Get all tasks
GET {{apiEndpoint}}/tasks

###

// Get task by ID
@taskId = 1
GET {{apiEndpoint}}/tasks/{{taskId}}

###

// Create a task
@taskTitle = My task
@taskDecription = Task desc
POST {{apiEndpoint}}/tasks
Content-Type: application/json

{
  "title": "{{taskTitle}}",
  "description": "{{taskDecription}}"
}

###

// Delete a task
@taskDeleteId = 2

DELETE {{apiEndpoint}}/tasks/{{taskDeleteId}}

###

// Update task status
@taskIdForUpdate = 1
@taskStatus = IN_PROGRESS

PATCH {{apiEndpoint}}/tasks/{{taskIdForUpdate}}/status
Content-Type: application/json

{
  "status": "{{taskStatus}}"
}

###

// Search

GET {{apiEndpoint}}/tasks?status=OPEN&searchTerm=Task
